# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_scraping', '0004_chat_all_members_are_administrators'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_shown',
            field=models.BooleanField(default=False),
        ),
    ]
