# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_scraping', '0007_auto_20170706_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='job_status',
            field=models.CharField(blank=True, choices=[(b'', b'Any'), (b'open', b'Open'), (b'completed', b'Completed'), (b'cancelled', b'Cancelled')], default=b'open', help_text=b'The current status of the Job', max_length=20),
        ),
    ]
